api_name: "https://api.deepai.org/api/image-editor"

source_file_type: "png"

img_source: "src/static/source"
img_cleaned: "src/static/source_cleaned"
img_dest: "src/static/dest"
img_presets: "src/static/presets"
img_placeholder_before: "static/img/placeholder_before.png"
img_placeholder_edited: "static/img/placeholder_edited.png"

email_from: "vojta.zahradnik@gmail.com"
email_subject: "Adastra AI"
email_mess: "Adastra AI generated image"

gmail_scopes:
    - "https://www.googleapis.com/auth/gmail.send"
gmail_creds: "src/creds/creds.json"