api_name: "https://api.deepai.org/api/image-editor"
port: "5001"
source_file_type: "png"
adastra_background: "src/static/img/adastra_border.png"

img_folders:
    source: "source"
    cleaned: "source_cleaned"
    croped: "source_croped"
    enhanced: "source_enhanced"
    dest: "dest"
    presets: "presets"

placeholders:
    before: "static/img/placeholder_before.png"
    edited: "static/img/placeholder_edited.png"

email:
    from: "vojta.zahradnik@gmail.com"
    subject: "Adastra AI"
    mess: "Adastra AI generated image"

gmail:
    scopes: ["https://www.googleapis.com/auth/gmail.send"]
    creds: "src/creds/creds.json"