api_name: "https://api.deepai.org/api/image-editor"

source_file_type: "png"

img_source: "static/source"
img_dest: "static/dest"
presets: "static/presets"
img_placeholder: "imgs/woman.png"

email_from: "vojta.zahradnik@gmail.com"
email_to: "vojta.zahradnik@gmail.com"
email_subject: "Adastra AI"
email_server: "127.0.0.1"